GarageLive/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Guest.urls')),  # 👈 DEFAULT HOMEPAGE
    path('admin/', admin.site.urls),
    
    path('Admin/',include('Admin.urls')),
    path('Guest/',include('Guest.urls')),
    path('User/',include('User.urls')),
    
    path('ServiceCenter/',include('ServiceCenter.urls')),
    path('Technician/',include('Technician.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Guest/urls.py
from django.urls import path
from Guest import views
app_name="Guest"

urlpatterns = [
    path('NewUser/',views.newuser,name="NewUser"),
    path('AjaxPlace/',views.AjaxPlace,name='AjaxPlace'),
    path('Login/',views.login,name='Login'),
    

    path('Servicecentereg/',views.servicecenter,name='servicecenter'),
    

    path('indexpage/',views.indexpage,name="indexpage"),
    path('',views.indexpage,name="indexpage"),

]

User/urls.py
from django.urls import path
from User import views

app_name="User"

urlpatterns = [
    path('MyProfile/',views.myprofile,name="MyProfile"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('ChangePassword/',views.changepassword,name="changepassword"),
    path('HomePage/',views.homepageview,name="HomePage"),
    path('Complaint/',views.complaint,name="complaint"),
    path('delcomplaint/<int:did>',views.delcomplaint,name="delcomplaint"),

    path('viewservicecenter/',views.viewservicecenter,name="viewservicecenter"),
    path('AjaxLocation/',views.AjaxLocation,name="AjaxLocation"),
    path('servicebooking/<int:sid>',views.servicebooking,name="servicebooking"),
    path('myservicerequest/',views.myservice_request,name="myservicerequest"),
    

    path('AjaxVehicle/',views.AjaxVehicle,name="AjaxVehicle"),
    path('vehicle/',views.vehicle,name="vehicle"),
    path('worknote/<int:bid>',views.worknote,name="worknote"),
    path('payment/<int:bid>',views.payment,name="payment"),
    path('invoice/<int:bid>',views.invoice,name="invoice"),
    path('view_vehicle/',views.view_vehicle,name="myvehicle"),

    path('delvehicle/<int:did>',views.del_vehicle,name="delvehicle"),
    path('logout/',views.logout,name="logout"),

    path('breakdownassist/',views.breakdown_assist,name='breakdownassist'),
    path('BreakdownBooking/<int:sid>',views.breakdown_booking,name='BreakdownBooking'),
    path('breakdown_status/',views.breakdown_status,name="breakdown_status"),
    path("breakdown-payment/<int:bs_id>/",views.breakdown_payment,name="breakdown_payment"),
    path("breakdown-invoice/<int:bs_id>/",views.breakdown_invoice,name="breakdown_invoice"),
    path('feedback/<int:bid>/',views.feedback,name="feedback"),
    path('edit-feedback/<int:fid>/',views.edit_feedback,name="edit_feedback"),
    path('delete-feedback/<int:fid>/',views.delete_feedback,name="delete_feedback"),
    path('service_history/<int:vid>/',views.service_history,name="service_history"),
    path('breakdown-status-api/', views.breakdown_status_api, name='breakdown_status_api'),
    path('myservice-request-api/', views.myservice_request_api, name='myservice_request_api'),
    



    
   
]

Guest/models.py
from django.db import models
from Admin.models import *

# Create your models here.
class tbl_user(models.Model):
    user_name=models.CharField(max_length=50)
    user_gender=models.CharField(max_length=50)
    contact_number=models.CharField(max_length=50)
    user_email=models.CharField(max_length=50)
    password=models.CharField(max_length=50)
    place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)
    address=models.CharField(max_length=50)
    image=models.FileField(upload_to='Assets/UserDocs/')
    user_status=models.IntegerField(default=0)


class tbl_seller(models.Model):
    user_name=models.CharField(max_length=50)
    contact_number=models.CharField(max_length=50)
    user_email=models.CharField(max_length=50)
    password=models.CharField(max_length=50)
    place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)
    estd_date=models.CharField(max_length=50)
    license_number=models.CharField(max_length=50)
    owner_name=models.CharField(max_length=50)
    license_proof=models.FileField(upload_to='Assets/SellerDocs/')
    owner_proof=models.FileField(upload_to='Assests/SellerDocs/')
    seller_status=models.IntegerField(default=0)




class tbl_servicecenter(models.Model):
    servicecenter_name=models.CharField(max_length=50)
    servicecenter_email=models.CharField(max_length=50)
    servicecenter_contact=models.CharField(max_length=50)
    servicecenter_address=models.CharField(max_length=50)
    servicecenter_logo=models.FileField(upload_to='Assets/ServicecenterDocs/')
    servicecenter_license=models.FileField(upload_to='Assets/ServicecenterDocs/')
    servicecenter_password=models.CharField(max_length=50)
    servicecenter_status=models.IntegerField(default=0)
    servicecenter_regdate=models.DateField(auto_now_add=True)
    place=models.ForeignKey(tbl_place,on_delete=models.CASCADE)

Guest/views.py
from django.shortcuts import render,redirect
from Admin.models import *
from Guest.models import *
from ServiceCenter.models import *
from django.core.mail import send_mail
from django.conf import settings


# Create your views here.

def newuser(request):
    
    placedata=tbl_place.objects.all()
    districtdata=tbl_district.objects.all()
    if request.method=="POST":
        name=request.POST.get("txt_name")
        gender=request.POST.get("gender")
        contact=request.POST.get("txt_contact")
        email=request.POST.get("txt_email")
        password=request.POST.get("txt_password")
        place=tbl_place.objects.get(id=request.POST.get("sel_place"))
        address=request.POST.get("txt_address")
        image=request.FILES.get("image")

        usercount=tbl_user.objects.filter(user_email=email).count()
        if usercount>0:
            return render(request,"Guest/NewUser.html",{'msg':"User already exists with this email"})
        else:

            userdata=tbl_user.objects.create(user_name=name,user_gender=gender,contact_number=contact,user_email=email,password=password,
            place=place,address=address,image=image)
            email=userdata.user_email
            subject = "Welcome to GarageLive 🚗"
            message = (
                "Dear User,\n\n"
                "Welcome to GarageLive!\n\n"
                "Your account has been successfully verified and approved by our admin team. "
                "You can now log in and start using all the features of GarageLive, including:\n\n"
                "• Booking vehicle services\n"
                "• Tracking service status\n"
                "• Managing your vehicle details\n"
                "• Easy communication with service centers\n\n"
                "If you face any issues or have questions, feel free to contact our support team.\n\n"
                "We’re excited to have you onboard!\n\n"
                "Warm regards,\n"
                "GarageLive Team"
            )

            send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )
            return render(request,"Guest/NewUser.html",{'msg':"User Registered"})
    else:
        return render(request,"Guest/NewUser.html",{'placedata':placedata,'districtdata':districtdata})


def AjaxPlace(request):
    districtid=request.GET.get('did')
    placedata=tbl_place.objects.filter(district=districtid)
    return render(request,'Guest/Ajaxplace.html',{'placedata':placedata})


def login(request):
    if request.method=="POST":
        email=request.POST.get("txt_email")
        password=request.POST.get("txt_password")
        
        usercount=tbl_user.objects.filter(user_email=email,password=password).count()
        admincount=tbl_AdminRegistration.objects.filter(admin_email=email,admin_password=password).count()
        
        
        
        centercount=tbl_servicecenter.objects.filter(servicecenter_email=email,servicecenter_password=password,servicecenter_status=1).count()
        techniciancount=tbl_technician.objects.filter(technician_email=email,technician_password=password).count()

        if usercount>0:
            userdata=tbl_user.objects.get(user_email=email,password=password)
            request.session['uid']=userdata.id
            return redirect("User:HomePage")
        

        elif admincount>0:
            admindata=tbl_AdminRegistration.objects.get(admin_email=email,admin_password=password)
            request.session['aid']=admindata.id
            return redirect("Admin:AdminHome")
        

        

        elif centercount>0:
            centerdata=tbl_servicecenter.objects.get(servicecenter_email=email,servicecenter_password=password)
            request.session['cid']=centerdata.id
            return redirect("ServiceCenter:HomePage")

        elif techniciancount>0:
            techniciandata=tbl_technician.objects.get(technician_email=email,technician_password=password)
            request.session['tid']=techniciandata.id
            return redirect("Technician:HomePage")
        else:
            return render(request,"Guest/Login.html",{'msg':"Invalid Login"})
        
    else:
        return render(request,'Guest/Login.html')




    
        

        


    
    


def servicecenter(request):
    placedata=tbl_place.objects.all()
    districtdata=tbl_district.objects.all()

    if request.method=="POST":
        name=request.POST.get("txt_name")
        email=request.POST.get("txt_email")
        number=request.POST.get("txt_contact")
        address=request.POST.get("txt_address")
        logo=request.FILES.get("file_logo")
        license_proof=request.FILES.get("file_license")
        password=request.POST.get("txt_password")
        place=tbl_place.objects.get(id=request.POST.get("sel_place"))

        servicecentercount=tbl_servicecenter.objects.filter(servicecenter_email=email).count()
        if servicecentercount>0:
            return render(request,"Guest/ServiceCenterReg.html",{'msg':"center with email already exists"})
        else:


            tbl_servicecenter.objects.create(servicecenter_name=name,servicecenter_email=email,servicecenter_contact=number,
            servicecenter_address=address,servicecenter_logo=logo,servicecenter_license=license_proof,servicecenter_password=password,
            place=place)
            return render(request,"Guest/ServiceCenterReg.html",{'msg':"Center Registered,wait for admin approval",'placedata':placedata,'districtdata':districtdata})
    else:
        return render(request,"Guest/ServiceCenterReg.html",{'placedata':placedata,'districtdata':districtdata})




def indexpage(request):
    return render(request,"Guest/index.html")

Guest/templates/Guest/AjaxPlace.html
    <option value="">----Select----</option>
    {% for i in placedata %}
    <option value="{{i.id}}">{{i.place_name}}</option>
    {% endfor %}

Guest/templates/Guest/Head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>GarageLive - Vehicle Repair Solution</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'Main/img/favicon.ico'%}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@600;700&family=Ubuntu:wght@400;500&display=swap" rel="stylesheet"> 

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'Main/lib/animate/animate.min.css'%}" rel="stylesheet">
    <link href="{% static 'Main/lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
    <link href="{% static 'Main/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css'%}" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'Main/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'Main/css/style.css'%}" rel="stylesheet">
</head>

<body>
    <!-- Spinner Start 
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    Spinner End -->


    <!-- Topbar Start -->
    <div class="container-fluid bg-light p-0">
        <div class="row gx-0 d-none d-lg-flex">
            <div class="col-lg-7 px-5 text-start">
                <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                    <small class="fa fa-map-marker-alt text-primary me-2"></small>
                    <small>Kerala,India</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center py-3">
                    <small class="far fa-clock text-primary me-2"></small>
                    <small>Mon - Sat : 09.00 AM - 09.00 PM</small>
                </div>
            </div>
            <div class="col-lg-5 px-5 text-end">
                <div class="h-100 d-inline-flex align-items-center py-3 me-4">
                    <small class="fa fa-phone-alt text-primary me-2"></small>
                    <small>+91 9562770822</small>
                </div>
                <div class="h-100 d-inline-flex align-items-center">
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-1" href=""><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-sm-square bg-white text-primary me-0" href=""><i class="fab fa-instagram"></i></a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
    
    <!-- Logo -->
    <a href="{% static 'Main/index.html'%}" 
       class="navbar-brand d-flex align-items-center px-4 px-lg-5">
        <h2 class="m-0 text-primary">
            <i class="fa fa-car me-3"></i>GarageLive
        </h2>
    </a>

    <!-- Toggle -->
    <button type="button" 
            class="navbar-toggler me-4" 
            data-bs-toggle="collapse" 
            data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapse Area -->
    <div class="collapse navbar-collapse" id="navbarCollapse">

        <!-- Nav Links -->
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="{% url 'Guest:indexpage' %}" class="nav-item nav-link active">Home</a>
            <a href="{% url 'Guest:NewUser' %}" class="nav-item nav-link">New User</a>
            <a href="{% url 'Guest:servicecenter' %}" class="nav-item nav-link">New Service center</a>
            <a href="{% url 'Guest:indexpage' %}#about" class="nav-item nav-link">About</a>
            <a href="{% url 'Guest:indexpage' %}#service" class="nav-item nav-link">Services</a>
            <a href="{% url 'Guest:indexpage' %}#contact" class="nav-item nav-link">Contact</a>
        </div>

        <!-- Login Button -->
        <div class="ms-lg-3 mt-3 mt-lg-0 px-4 px-lg-0">
            <a href="{% url 'Guest:Login' %}" 
               class="btn btn-primary w-100 d-flex justify-content-center align-items-center py-3 px-4">
                Log in <i class="fa fa-arrow-right ms-2"></i>
            </a>
        </div>

    </div>
</nav>

    
    
    
    <!-- Navbar End -->
     {% block content %}
     <div align="center">

     </div>
     {% endblock content %}
     <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Address</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Kerala,India</p>
                    <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+91 9562770822</p>
                    <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@GarageLive.com</p>
                    <div class="d-flex pt-2">
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Opening Hours</h4>
                    <h6 class="text-light">Monday - Saturday:</h6>
                    <p class="mb-4">09.00 AM - 09.00 PM</p>
                    <h6 class="text-light">Sunday:</h6>
                    <p class="mb-0">09.00 AM - 12.00 PM</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Services</h4>
                    <a class="btn btn-link" href="">Diagnostic Test</a>
                    <a class="btn btn-link" href="">Engine Servicing</a>
                    <a class="btn btn-link" href="">Tires Replacement</a>
                    <a class="btn btn-link" href="">Oil Changing</a>
                    <a class="btn btn-link" href="">Vacuam Cleaning</a>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h4 class="text-light mb-4">Newsletter</h4>
                    <p>sign up to get updates and offers.</p>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                        <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="copyright">
                <div class="row">
                    <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                        &copy; <a class="border-bottom" href="#">GarageLive</a>, All Right Reserved.

               
                    </div>
                    <div class="col-md-6 text-center text-md-end">
                        <div class="footer-menu">
                            <a href="">Home</a>
                            <a href="">Cookies</a>
                            <a href="">Help</a>
                            <a href="">FQAs</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'Main/lib/wow/wow.min.js'%}"></script>
    <script src="{% static 'Main/lib/easing/easing.min.js'%}"></script>
    <script src="{% static 'Main/lib/waypoints/waypoints.min.js'%}"></script>
    <script src="{% static 'Main/lib/counterup/counterup.min.js'%}"></script>
    <script src="{% static 'Main/lib/owlcarousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'Main/lib/tempusdominus/js/moment.min.js'%}"></script>
    <script src="{% static 'Main/lib/tempusdominus/js/moment-timezone.min.js'%}"></script>
    <script src="{% static 'Main/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js'%}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'Main/js/main.js'%}"></script>
</body>

</html>

Guest/templates/Guest/Login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>GarageLive</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	
	<link rel="stylesheet" href="{% static 'Login/css/style.css'%}">

	</head>
	<body class="img js-fullheight" style="background-image: url('{% static "Login/images/bg2.jpg" %}');">
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-4">
					<div class="login-wrap p-0">
		      	<h3 class="mb-4 text-center">Have an account?</h3>
		      	<form method="post" class="signin-form">
                    {% csrf_token %}
		      		<div class="form-group">
		      			<input type="text" class="form-control" name="txt_email" placeholder="e-mail" required>
		      		</div>
	            <div class="form-group">
	              <input id="password-field" type="password"  name="txt_password" class="form-control" placeholder="Password" required>
	              <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
	            </div>
	            <div class="form-group">
	            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
	            </div>
	           
	          </form>
	          <p class="w-100 text-center">&mdash; New Registartion &mdash;</p>
	          <div class="social d-flex text-center">
	          	<a href="{% url 'Guest:NewUser' %}" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span>New User</a>
	          	<a href="{% url 'Guest:servicecenter' %}" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> New Service Center</a>
				
	          </div>
		      </div>
				</div>
			</div>
		</div>
	</section>

	<script src="{% static 'Login/js/jquery.min.js'%}"></script>
  <script src="{% static 'Login/js/popper.js'%}"></script>
  <script src="{% static 'Login/js/bootstrap.min.js'%}"></script>
  <script src="{% static 'Login/js/main.js'%}"></script>

	</body>
</html>

{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'Guest:Login' %}";
</script>
{% endif %}

Guest/templates/Guest/NewSeller.html
{% extends 'Guest/Head.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NewSeller</title>
    
</head>
<body>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table border="1"><tr>
            <td>Name</td>
            <td><input type="text" name="txt_name" id=""></td>
        </tr>
        <tr>
            <td>contact_number</td>
            <td><input type="text" name="txt_number" id=""></td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td><input type="text" name="txt_email" id=""></td>
        </tr>
        <tr>
            <td>Password</td>
            <td><input type="password" name="txt_password" id=""></td>
        </tr>
         <tr>
            <td>Confirm Password</td>
            <td><input type="password" name="conf_password" id=""></td>
        </tr>
        <tr>
            <td>District</td>
            <td>
                 <select name="sel_district" id="sel_district">
                    <option  value="">select district</option>
                    {% for i in districtdata %}
                    <option 
                    value="{{i.id}}">{{i.district_name}}</option>
                    {% endfor %} 
                </select>
            </td>
        </tr>
        <tr>
            <td>Place</td>
            <td>
                 <select name="sel_place" id="sel_place">
                    <option  value="">----select place----</option>
                    
                </select>
            </td>
        </tr>
        <tr>
            <td>Estd Date</td>
            <td><input type="date" name="estd_date" id=""></td>
        </tr>
        <tr>
            <td>License Number</td>
            <td><input type="text" name="txt_license" id=""></td>
        </tr>
        <tr>
            <td>Owner Name</td>
            <td><input type="text" name="txt_owner" id=""></td>
        </tr>
        <tr>
            <td>License Proof</td>
            <td><input type="file" name="license" id=""></td>
        </tr>
        <tr>
            <td>Owner Proof</td>
            <td><input type="file" name="owner" id=""></td>
        </tr>
        <tr>
            <td><input type="submit" value="submit"></td>
            <td><input type="button"  value="Cancel" onclick="window.location='{% url 'Guest:NewSeller' %}'"></td>
        </tr>
       </table>
    </form>
</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $('#sel_district').change(function () {
        var did = $(this).val();
        var ur = "{% url 'Guest:AjaxPlace' %}"
        $.ajax({
            url: ur,
            data: { did: did },
            success: function (data) {
                $('#sel_place').html(data);
            }
        });
    });
</script>
</html>


{% if msg %}
<script>
    alert("{{msg}}")
    
</script>
{% endif %}

{% endblock content %}