GarageLive/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Guest.urls')),  # 👈 DEFAULT HOMEPAGE
    path('admin/', admin.site.urls),
    
    path('Admin/',include('Admin.urls')),
    path('Guest/',include('Guest.urls')),
    path('User/',include('User.urls')),
    
    path('ServiceCenter/',include('ServiceCenter.urls')),
    path('Technician/',include('Technician.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Technician/urls.py
from django.urls import path
from Technician import views

app_name="Technician"

urlpatterns = [
     path('HomePage/',views.homepage,name="HomePage"),
     path('profile/',views.profile,name="profile"),
     path('editprofile/',views.editprofile,name="editprofile"),
     path('changepassword/',views.changepassword,name="changepassword"),
     path('assignedjobs/',views.assigned_jobs,name="assigned_jobs"),
     path('startwork/<int:sid>',views.startwork,name="startwork"),
     path('startdiagnosis/<int:did>',views.start_diagnosis,name="start_diagnosis"),
     path('diagnosis_completed/<int:cdid>',views.diagnosis_completed,name="diagnosis_completed"),
     path('repair_progress/<int:rid>',views.repair_progress,name="repair_progress"),
     path('parts_replaced/<int:pid>',views.parts_replaced,name="parts_replaced"),
     path('testing_QA/<int:tid>',views.testing_QA,name="testing_QA"),
     path('service_completed/<int:sid>',views.service_completed,name="service_completed"),
     path('out_delivery/<int:did>',views.out_delivery,name="out_delivery"),
     # path('delivered/<int:did>',views.delivered,name="delivered"),
     path('workdescription/<int:bid>',views.workdescription,name="workdescription"),
     path('logout/',views.logout,name="logout"),

     path('update-service-cost/<int:booking_id>/', views.update_service_cost, name='update_service_cost'),

     path('breakdown-jobs/',views.breakdown_jobs,name='breakdown_jobs'),
      
     path('breakdown-step/<int:sid>/', views.update_breakdown_step, name='update_breakdown_step'),
     path('update_breakdown_charge/<int:bs_id>',views.update_breakdown_charge,name="update_breakdown_charge"),

    




     
]

User/urls.py
from django.urls import path
from User import views

app_name="User"

urlpatterns = [
    path('MyProfile/',views.myprofile,name="MyProfile"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('ChangePassword/',views.changepassword,name="changepassword"),
    path('HomePage/',views.homepageview,name="HomePage"),
    path('Complaint/',views.complaint,name="complaint"),
    path('delcomplaint/<int:did>',views.delcomplaint,name="delcomplaint"),

    path('viewservicecenter/',views.viewservicecenter,name="viewservicecenter"),
    path('AjaxLocation/',views.AjaxLocation,name="AjaxLocation"),
    path('servicebooking/<int:sid>',views.servicebooking,name="servicebooking"),
    path('myservicerequest/',views.myservice_request,name="myservicerequest"),
    

    path('AjaxVehicle/',views.AjaxVehicle,name="AjaxVehicle"),
    path('vehicle/',views.vehicle,name="vehicle"),
    path('worknote/<int:bid>',views.worknote,name="worknote"),
    path('payment/<int:bid>',views.payment,name="payment"),
    path('invoice/<int:bid>',views.invoice,name="invoice"),
    path('view_vehicle/',views.view_vehicle,name="myvehicle"),

    path('delvehicle/<int:did>',views.del_vehicle,name="delvehicle"),
    path('logout/',views.logout,name="logout"),

    path('breakdownassist/',views.breakdown_assist,name='breakdownassist'),
    path('BreakdownBooking/<int:sid>',views.breakdown_booking,name='BreakdownBooking'),
    path('breakdown_status/',views.breakdown_status,name="breakdown_status"),
    path("breakdown-payment/<int:bs_id>/",views.breakdown_payment,name="breakdown_payment"),
    path("breakdown-invoice/<int:bs_id>/",views.breakdown_invoice,name="breakdown_invoice"),
    path('feedback/<int:bid>/',views.feedback,name="feedback"),
    path('edit-feedback/<int:fid>/',views.edit_feedback,name="edit_feedback"),
    path('delete-feedback/<int:fid>/',views.delete_feedback,name="delete_feedback"),
    path('service_history/<int:vid>/',views.service_history,name="service_history"),
    path('breakdown-status-api/', views.breakdown_status_api, name='breakdown_status_api'),
    path('myservice-request-api/', views.myservice_request_api, name='myservice_request_api'),
    



    
   
]

Technician/models.py
from django.db import models
from User.models import *

# Create your models here.

class tbl_workedescription(models.Model):
    workedesc_content=models.CharField(max_length=50)
    booking=models.ForeignKey(tbl_booking,on_delete=models.CASCADE)
    
    

Technician/views.py
from django.shortcuts import render,redirect
from ServiceCenter.models import *
from User.models import *
from Technician.models import *
from decimal import Decimal



# Create your views here.


def homepage(request):
     if 'tid' not in request.session:
      return redirect("Guest:Login")
     else:
        greeting=tbl_technician.objects.get(id=request.session['tid'])
        techniciandata=tbl_technician.objects.get(id=request.session['tid'])
        assigned_service_jobs=tbl_booking.objects.filter(technician=techniciandata,booking_status__gte=1,booking_status__lte=10).prefetch_related('tbl_booking_services_set')
        
        assigned_breakdown_jobs=tbl_breakdownassist.objects.filter(technician=techniciandata,breakdown_status=1)
        completed_service_count=tbl_booking.objects.filter(technician=techniciandata,booking_status=12).count()
        completed_breakdown_count=tbl_breakdownassist.objects.filter(technician=techniciandata,breakdown_status=3).count()
        



        return render(request,"Technician/HomePage.html",{'data':techniciandata,'greeting':greeting,
        "assigned_service_jobs": assigned_service_jobs,
        "assigned_breakdown_jobs": assigned_breakdown_jobs,
        "assigned_total": assigned_service_jobs.count() + assigned_breakdown_jobs.count(),
        "total_completed": completed_service_count + completed_breakdown_count})

def profile(request):
     if 'tid' not in request.session:
      return redirect("Guest:Login")
     else:
        technician=tbl_technician.objects.get(id=request.session['tid'])
        greeting=tbl_technician.objects.get(id=request.session['tid'])
        return render(request,"Technician/Profile.html",{'data':technician,'greeting':greeting})


def editprofile(request):
     if 'tid' not in request.session:
      return redirect("Guest:Login")
     else:
        editprofile=tbl_technician.objects.get(id=request.session['tid'])
        greeting=tbl_technician.objects.get(id=request.session['tid'])
        if request.method=="POST":
            name=request.POST.get("txt_name")
            email=request.POST.get("txt_email")
            contact=request.POST.get("txt_contact")
            photo=request.FILES.get("file_photo")
            editprofile.technician_name=name
            editprofile.technician_email=email
            editprofile.technician_contact=contact
            editprofile.technician_photo=photo
            editprofile.save()
            return render(request,"Technician/Profile.html",{'msg':"Record Updated"})
        else:
            return render(request,"Technician/EditProfile.html",{'data':editprofile},{'greeting':greeting})


def changepassword(request):
     if 'tid' not in request.session:
      return redirect("Guest:Login")
     else:
        changepass=tbl_technician.objects.get(id=request.session['tid'])
        greeting=tbl_technician.objects.get(id=request.session['tid'])
        dbpass=changepass.technician_password
        if request.method=="POST":
            old=request.POST.get("txt_password")
            new=request.POST.get("new_password")
            confirm=request.POST.get("confirm_password")
            if old==dbpass:
                if new==confirm:
                    changepass.technician_password=new
                    changepass.save()
                    return render(request,"Technician/Profile.html",{'msg':"Password updated"})
                else:
                    return render(request,"Technician/ChangePassword.html",{'msg':"Invalid Password"})
            else:
                return render(request,"Technician/ChangePassword.html",{'msg':"Passwords doesn't match"})
        else:
            return render(request,"Technician/ChangePassword.html",{'greeting':greeting})




def assigned_jobs(request):
    if 'tid' not in request.session:
      return redirect("Guest:Login")
    else:
        greeting=tbl_technician.objects.get(id=request.session['tid'])
        jobdata=tbl_booking.objects.filter(technician=request.session['tid']).order_by('-id') 
        for booking in jobdata:
            booking.services = tbl_booking_services.objects.filter(booking=booking)

        return render(request,"Technician/Jobs.html",{'data':jobdata,'greeting':greeting})


def startwork(request,sid):
    data=tbl_booking.objects.get(id=sid)
    data.booking_status=3
    data.save()
    return redirect("Technician:assigned_jobs")


def start_diagnosis(request,did):
    data=tbl_booking.objects.get(id=did)
    data.booking_status=4
    data.save()
    return redirect("Technician:assigned_jobs")

def diagnosis_completed(request,cdid):
    data=tbl_booking.objects.get(id=cdid)
    data.booking_status=5
    data.save()
    return redirect("Technician:assigned_jobs")

def repair_progress(request,rid):
    data=tbl_booking.objects.get(id=rid)
    data.booking_status=6
    data.save()
    return redirect("Technician:assigned_jobs")

def parts_replaced(request,pid):
    data=tbl_booking.objects.get(id=pid)
    data.booking_status=7
    data.save()
    return redirect("Technician:assigned_jobs")

def testing_QA(request,tid):
    data=tbl_booking.objects.get(id=tid)
    data.booking_status=8
    data.save()
    return redirect("Technician:assigned_jobs")

def service_completed(request,sid):
    data=tbl_booking.objects.get(id=sid)
    data.booking_status=9
    data.save()
    return redirect("Technician:assigned_jobs")

def out_delivery(request,did):
    data=tbl_booking.objects.get(id=did)
    data.booking_status=10
    data.save()
    return redirect("Technician:assigned_jobs")

# def delivered(request,did):
#     data=tbl_booking.objects.get(id=did)
#     data.booking_status=12
#     data.save()
#     return render(request,"Technician/Jobs.html",{'msg':"Vehicle Delivered"})
    


def workdescription(request,bid):
    greeting=tbl_technician.objects.get(id=request.session['tid'])
    bookingdata=tbl_booking.objects.get(id=bid)    
    notes=tbl_workedescription.objects.filter(booking=bookingdata)
    if request.method=="POST":
        work=request.POST.get("txt_work")
        tbl_workedescription.objects.create(workedesc_content=work,booking=bookingdata)
        return render(request,"Technician/Jobs.html",{'msg':"Note Added"})

    else:
        return render(request,"Technician/WorkDescription.html",{'notes':notes,'greeting':greeting})



def logout(request):
    del request.session['tid']
    return redirect("Guest:Login")



def update_service_cost(request, booking_id):

    booking = tbl_booking.objects.get(id=booking_id)
    greeting=tbl_technician.objects.get(id=request.session['tid'])
    services = tbl_booking_services.objects.filter(booking=booking)
    if booking.booking_status >= 10:
        return redirect("Technician:assigned_jobs")
    
    else:


        if request.method == "POST":
            for service in services:
                labour = request.POST.get(f"labour_{service.id}")
                parts = request.POST.get(f"parts_{service.id}")

                service.labour_charge = Decimal(labour)
                service.parts_charge = Decimal(parts)
                service.final_amount = (
                    service.base_amount +
                    service.labour_charge +
                    service.parts_charge 
                    
                )
                service.save()

            return redirect("Technician:assigned_jobs")

    return render(
        request,
        "Technician/ServiceCost.html",
        {
            "booking": booking,
            "services": services,'greeting':greeting
        }
    )




def breakdown_jobs(request):
    if 'tid' not in request.session:
        return redirect("Guest:Login")
    greeting=tbl_technician.objects.get(id=request.session['tid'])
    data = tbl_breakdown_booking_services.objects.filter(booking__technician_id=request.session['tid']).order_by('-id')
    return render(request, "Technician/BreakdownJobs.html", {'data': data,'greeting':greeting})


def update_breakdown_step(request, sid):
    service = tbl_breakdown_booking_services.objects.get(id=sid)
    service.progress_step += 1
    service.save()
    return redirect("Technician:breakdown_jobs")


def update_breakdown_charge(request, bs_id):
    bs = tbl_breakdown_booking_services.objects.get(id=bs_id)
    breakdown_bs = tbl_breakdownassist.objects.get(id=bs.booking_id)
    greeting=tbl_technician.objects.get(id=request.session['tid'])
    

    if bs.progress_step < 1:
        return redirect("Technician:breakdown_jobs")

    if request.method == "POST":
        extra = Decimal(request.POST.get("extra_charge", 0))

        bs.extra_charge = extra
        bs.final_amount = bs.base_amount + extra
        bs.progress_step += 1
        bs.billing_status = True
        breakdown_bs.breakdown_status = 3
        bs.save()
        breakdown_bs.save()

        total_amount=bs.final_amount
        breakdown_booking=bs.booking
        servicecenter=breakdown_booking.servicecenter

        if not tbl_commision.objects.filter(booking_type=2,booking_id=breakdown_booking.id).exists():
            admin_amount=total_amount * Decimal('0.05')

            tbl_commision.objects.create(
                servicecenter=servicecenter,
                booking_type=2,
                booking_id=breakdown_booking.id,
                admin_commision=admin_amount,
            )
            

        

        return redirect("Technician:breakdown_jobs")

    return render(request, "Technician/UpdateBreakdownCharge.html", {
        "data": bs,'greeting':greeting
    })

Technician/templates/Technician/ChangePassword.html
{% extends 'Technician/Head_tech.html' %}
{% block content %}

<style>
  .hint-text{ font-size: .85rem; color: #6c757d; }
</style>

<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">
      <div class="col-lg-6 mx-auto grid-margin stretch-card">
        <div class="card">
          <div class="card-body">

            <div class="d-flex align-items-center justify-content-between mb-2">
              <div>
                <h4 class="card-title mb-1">Change Password</h4>
                <p class="card-description mb-0">Update your password securely</p>
              </div>
              <a href="{% url 'Technician:profile' %}" class="btn btn-light">Back</a>
            </div>

            <hr>

            <form method="post" class="forms-sample">
              {% csrf_token %}

              <div class="form-group">
                <label for="old_password">Old Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="old_password"
                  name="txt_password"
                  placeholder="Enter old password"
                  required
                >
              </div>

              <div class="form-group">
                <label for="new_password">New Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="new_password"
                  name="new_password"
                  placeholder="Enter new password"
                  required
                >
                <div class="hint-text mt-2">Use a strong password with letters, numbers, and symbols.</div>
              </div>

              <div class="form-group">
                <label for="confirm_password">Re-Type Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="confirm_password"
                  name="confirm_password"
                  placeholder="Re-enter new password"
                  required
                >
              </div>

              <button type="submit" class="btn btn-primary me-2">
                Change Password
              </button>
              <a href="{% url 'Technician:profile' %}" class="btn btn-light">
                Cancel
              </a>

            </form>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'Technician:changepassword' %}";
</script>
{% endif %}

{% endblock content %}

Technician/templates/Technician/Head_tech.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>GarageLive Technician</title>

  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'Technician/vendors/feather/feather.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/vendors/mdi/css/materialdesignicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/vendors/ti-icons/css/themify-icons.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/vendors/typicons/typicons.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/vendors/simple-line-icons/css/simple-line-icons.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/vendors/css/vendor.bundle.base.css' %}">
  <!-- endinject -->

  <!-- Plugin css for this page -->
  <link rel="stylesheet" href="{% static 'Technician/vendors/datatables.net-bs4/dataTables.bootstrap4.css' %}">
  <link rel="stylesheet" href="{% static 'Technician/js/select.dataTables.min.css' %}">
  <!-- End plugin css for this page -->

  <!-- inject:css -->
  <link rel="stylesheet" href="{% static 'Technician/css/vertical-layout-light/style.css' %}">
  <!-- endinject -->

  <link rel="shortcut icon" href="{% static 'Technician/images/favicon.png' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

  <style>
  .table .btn.btn-sm{
    border-width: 1px;
    border-radius: 8px;
    padding: 0.35rem 0.65rem;
    line-height: 1.2;
  }

  
</style>

</head>

<body>
<div class="container-scroller">

  <!-- NAVBAR -->
  <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
      <div class="me-3">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
          <span class="icon-menu"></span>
        </button>
      </div>
      <div>
        <a class="navbar-brand brand-logo" href="{% url 'Technician:HomePage' %}">
          <img src="{% static 'Technician/images/GarageLive_logo.png' %}" alt="logo">
        </a>
      </div>
    </div>

    <div class="navbar-menu-wrapper d-flex align-items-top">
      <ul class="navbar-nav">
       <li class="nav-item font-weight-semibold ms-0">

          <h1 class="welcome-text">
            <span id="greeting"></span>,
            <span class="text-black fw-bold">{{ greeting.technician_name }}</span>
          </h1>
         
        </li>
      </ul>

      <ul class="navbar-nav ms-auto">
        
        

        
        
        <li class="nav-item dropdown user-dropdown">

          <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
            <img class="img-xs rounded-circle" src="{{ greeting.technician_photo.url }}" alt="Profile image">
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <div class="dropdown-header text-center">
              <img class="img-xs rounded-circle" src="{{ greeting.technician_photo.url }}" alt="Profile image">
              <p class="mb-1 mt-3 font-weight-semibold">{{greeting.technician_name}}</p>
              <p class="fw-light text-muted mb-0">{{greeting.technician_email}}</p>
            </div>
            <a class="dropdown-item" href="{% url 'Technician:profile' %}"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile</a>

            <a class="dropdown-item" href="{% url 'Technician:logout' %}"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i> Sign Out</a>
          </div>
        </li>
      </ul>

      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
        <span class="mdi mdi-menu"></span>
      </button>
    </div>
  </nav>
  <!-- NAVBAR END -->

  <div class="container-fluid page-body-wrapper">

    <!-- SETTINGS PANEL -->
    <div class="theme-setting-wrapper">
      <div id="settings-trigger"><i class="ti-settings"></i></div>
      <div id="theme-settings" class="settings-panel">
        <i class="settings-close ti-close"></i>
        <p class="settings-heading">SIDEBAR SKINS</p>
        <div class="sidebar-bg-options selected" id="sidebar-light-theme">
          <div class="img-ss rounded-circle bg-light border me-3"></div>Light
        </div>
        <div class="sidebar-bg-options" id="sidebar-dark-theme">
          <div class="img-ss rounded-circle bg-dark border me-3"></div>Dark
        </div>
        <p class="settings-heading mt-2">HEADER SKINS</p>
        <div class="color-tiles mx-0 px-4">
          <div class="tiles success"></div>
          <div class="tiles warning"></div>
          <div class="tiles danger"></div>
          <div class="tiles info"></div>
          <div class="tiles dark"></div>
          <div class="tiles default"></div>
        </div>
      </div>
    </div>

   
    <!-- SETTINGS PANEL END -->

    <!-- SIDEBAR -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Technician:HomePage' %}">
            <i class="menu-icon fa-solid fa-tachometer-alt"></i>
            <span class="menu-title">Dashboard</span>
          </a>
        </li>

        <li class="nav-item nav-category">Manage</li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'Technician:profile' %}">
            <i class="menu-icon fa-solid fa-user-circle"></i>
            <span class="menu-title">My Profile</span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'Technician:assigned_jobs' %}">
            <i class="menu-icon fa-solid fa-briefcase"></i>
            <span class="menu-title">My Jobs</span>
          </a>
        </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'Technician:breakdown_jobs' %}">
              <i class="menu-icon fa-solid - fa-triangle-exclamation"></i>
              <span class="menu-title">Breakdown Jobs</span>
            </a>
          </li>


       
      </ul>
    </nav>
    <!-- SIDEBAR END -->

    <!-- ✅ MAIN PANEL (THIS FIXES FOOTER POSITION) -->
    <div class="main-panel">
      <div class="content-wrapper">
        {% block content %}
        {% endblock content %}
      </div>

      
    </div>
    <!-- main-panel ends -->

  </div>
  <!-- page-body-wrapper ends -->

</div>
<!-- container-scroller -->

<script>
  function getGreeting() {
    const hour = new Date().getHours();
    if (hour < 12) return "Good Morning";
    if (hour < 18) return "Good Afternoon";
    return "Good Evening";
  }
  const g = document.getElementById("greeting");
  if (g) g.textContent = getGreeting();
</script>

<!-- plugins:js -->
<script src="{% static 'Technician/vendors/js/vendor.bundle.base.js' %}"></script>
<!-- endinject -->

<!-- Plugin js for this page -->
<script src="{% static 'Technician/vendors/chart.js/Chart.min.js' %}"></script>
<script src="{% static 'Technician/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'Technician/vendors/progressbar.js/progressbar.min.js' %}"></script>
<!-- End plugin js for this page -->

<!-- inject:js -->
<script src="{% static 'Technician/js/off-canvas.js' %}"></script>
<script src="{% static 'Technician/js/hoverable-collapse.js' %}"></script>
<script src="{% static 'Technician/js/template.js' %}"></script>
<script src="{% static 'Technician/js/settings.js' %}"></script>
<script src="{% static 'Technician/js/todolist.js' %}"></script>
<!-- endinject -->

<!-- Custom js for this page -->
<script src="{% static 'Technician/js/dashboard.js' %}"></script>
<script src="{% static 'Technician/js/Chart.roundedBarCharts.js' %}"></script>
<!-- End custom js for this page -->

<script>
document.addEventListener("DOMContentLoaded", function () {

    const body = document.body;
    const toggleBtn = document.querySelector('[data-bs-toggle="minimize"]');

    // 🔹 Apply saved state on load
    const savedState = localStorage.getItem("sidebarState");
    if (savedState === "collapsed") {
        body.classList.add("sidebar-icon-only");
    }

    // 🔹 Save state when toggled
    if (toggleBtn) {
        toggleBtn.addEventListener("click", function () {
            setTimeout(function () {
                if (body.classList.contains("sidebar-icon-only")) {
                    localStorage.setItem("sidebarState", "collapsed");
                } else {
                    localStorage.setItem("sidebarState", "expanded");
                }
            }, 300);
        });
    }

});
</script>

</body>
</html>

Technician/templates/Technician/Profile.html
{% extends 'Technician/Head_tech.html' %}
{% block content %}

<style>
  .profile-avatar{
    width: 92px;
    height: 92px;
    border-radius: 18px;
    object-fit: cover;
    border: 1px solid rgba(0,0,0,.10);
    background: #fff;
  }
  .kv-label{
    font-size: .78rem;
    font-weight: 600;
    letter-spacing: .02em;
    color: #6c757d;
    margin-bottom: 6px;
  }
  .kv-value{
    background: #f8f9fa;
    border: 1px solid rgba(0,0,0,.08);
    border-radius: 14px;
    padding: 12px 14px;
    color: #212529;
    line-height: 1.35;
    word-break: break-word;
  }
  .info-grid{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
  }
  @media (max-width: 992px){
    .info-grid{ grid-template-columns: 1fr; }
  }
</style>

<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">
      <div class="col-lg-8 mx-auto grid-margin stretch-card">
        <div class="card">
          <div class="card-body">

            <!-- Header -->
            <div class="d-flex align-items-center justify-content-between flex-wrap mb-3">
              <div class="d-flex align-items-center">
                <div class="me-3">
                  <img src="{{ data.technician_photo.url }}" alt="Profile" class="profile-avatar">
                </div>
                <div>
                  <h4 class="card-title mb-1">{{ data.technician_name }}</h4>
                  <p class="card-description mb-0">Technician Profile</p>
                </div>
              </div>

              <div class="d-flex mt-2 mt-md-0">
                <a href="{% url 'Technician:editprofile' %}" class="btn btn-outline-primary me-2">
                  Edit Profile
                </a>
                <a href="{% url 'Technician:changepassword' %}" class="btn btn-outline-primary">
                  Change Password
                </a>
              </div>
            </div>

            <hr>

            <!-- Profile Details -->
            <div class="info-grid mt-4">

              <div>
                <div class="kv-label">Technician Name</div>
                <div class="kv-value">{{ data.technician_name }}</div>
              </div>

              <div>
                <div class="kv-label">Email</div>
                <div class="kv-value">{{ data.technician_email }}</div>
              </div>

              <div>
                <div class="kv-label">Contact</div>
                <div class="kv-value">{{ data.technician_contact }}</div>
              </div>

              <div>
                <div class="kv-label">Service Center</div>
                <div class="kv-value">
                  {% if data.servicecenter %}
                    {{ data.servicecenter.servicecenter_name }}
                  {% else %}
                    Not Assigned
                  {% endif %}
                </div>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'Technician:profile' %}";
</script>
{% endif %}

{% endblock content %}