GarageLive/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Guest.urls')),  # 👈 DEFAULT HOMEPAGE
    path('admin/', admin.site.urls),
    
    path('Admin/',include('Admin.urls')),
    path('Guest/',include('Guest.urls')),
    path('User/',include('User.urls')),
    
    path('ServiceCenter/',include('ServiceCenter.urls')),
    path('Technician/',include('Technician.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from User import views

app_name="User"

urlpatterns = [
    path('MyProfile/',views.myprofile,name="MyProfile"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('ChangePassword/',views.changepassword,name="changepassword"),
    path('HomePage/',views.homepageview,name="HomePage"),
    path('Complaint/',views.complaint,name="complaint"),
    path('delcomplaint/<int:did>',views.delcomplaint,name="delcomplaint"),

    path('viewservicecenter/',views.viewservicecenter,name="viewservicecenter"),
    path('AjaxLocation/',views.AjaxLocation,name="AjaxLocation"),
    path('servicebooking/<int:sid>',views.servicebooking,name="servicebooking"),
    path('myservicerequest/',views.myservice_request,name="myservicerequest"),
    

    path('AjaxVehicle/',views.AjaxVehicle,name="AjaxVehicle"),
    path('vehicle/',views.vehicle,name="vehicle"),
    path('worknote/<int:bid>',views.worknote,name="worknote"),
    path('payment/<int:bid>',views.payment,name="payment"),
    path('invoice/<int:bid>',views.invoice,name="invoice"),
    path('view_vehicle/',views.view_vehicle,name="myvehicle"),

    path('delvehicle/<int:did>',views.del_vehicle,name="delvehicle"),
    path('logout/',views.logout,name="logout"),

    path('breakdownassist/',views.breakdown_assist,name='breakdownassist'),
    path('BreakdownBooking/<int:sid>',views.breakdown_booking,name='BreakdownBooking'),
    path('breakdown_status/',views.breakdown_status,name="breakdown_status"),
    path("breakdown-payment/<int:bs_id>/",views.breakdown_payment,name="breakdown_payment"),
    path("breakdown-invoice/<int:bs_id>/",views.breakdown_invoice,name="breakdown_invoice"),
    path('feedback/<int:bid>/',views.feedback,name="feedback"),
    path('edit-feedback/<int:fid>/',views.edit_feedback,name="edit_feedback"),
    path('delete-feedback/<int:fid>/',views.delete_feedback,name="delete_feedback"),
    path('service_history/<int:vid>/',views.service_history,name="service_history"),
    path('breakdown-status-api/', views.breakdown_status_api, name='breakdown_status_api'),
    path('myservice-request-api/', views.myservice_request_api, name='myservice_request_api'),
    



    
   
]

User/models.py
from django.db import models
from Guest.models import *
from Admin.models import *
from ServiceCenter.models import *



# Create your models here.

class tbl_complaint(models.Model):
    complaint_title=models.CharField(max_length=50)
    complaint_content=models.CharField(max_length=50)
    complaint_date=models.DateField(auto_now_add=True)
    complaint_reply=models.CharField(max_length=50,null=True)
    complaint_status=models.IntegerField(default=0)
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)




class tbl_vehicle(models.Model):
    vehicle_number=models.CharField(max_length=50)
    vehicle_year=models.CharField(max_length=50)
    vehicle_photo=models.FileField(upload_to='Assets/VehicleDocs/')
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)
    model=models.ForeignKey(tbl_model,on_delete=models.CASCADE)

class tbl_booking(models.Model):
    booking_date=models.DateField(auto_now_add=True)
    booking_todate=models.DateField()
    
    booking_status=models.IntegerField(default=0)
    booking_complaints=models.CharField(max_length=50)
            
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)
    servicecenter=models.ForeignKey(tbl_servicecenter,on_delete=models.CASCADE)
    vehicle=models.ForeignKey(tbl_vehicle,on_delete=models.CASCADE)
    technician=models.ForeignKey(tbl_technician,on_delete=models.CASCADE,null=True)



class tbl_booking_services(models.Model):
    booking=models.ForeignKey(tbl_booking,on_delete=models.CASCADE)
    servicecenter_services=models.ForeignKey(tbl_servicecenterservices,on_delete=models.CASCADE)
    base_amount=models.DecimalField(max_digits=10, decimal_places=2)
    labour_charge = models.DecimalField(max_digits=10, decimal_places=2, default=0,null=True)
    parts_charge = models.DecimalField(max_digits=10, decimal_places=2, default=0,null=True)
    final_amount = models.DecimalField(max_digits=10, decimal_places=2,null=True)





class tbl_breakdownassist(models.Model):
    breakdown_date=models.DateField(auto_now_add=True)
    breakdown_complaint=models.CharField(max_length=50)
    user=models.ForeignKey(tbl_user,on_delete=models.CASCADE)
    vehicle=models.ForeignKey(tbl_vehicle,on_delete=models.CASCADE)
    servicecenter=models.ForeignKey(tbl_servicecenter,on_delete=models.CASCADE)
    technician=models.ForeignKey(tbl_technician,on_delete=models.CASCADE,null=True)
    breakdown_status=models.IntegerField(default=0)



class tbl_breakdown_booking_services(models.Model):
    booking = models.ForeignKey(tbl_breakdownassist,on_delete=models.CASCADE)

    servicecenter_breakdown_service = models.ForeignKey(tbl_servicecenter_breakdown_services,on_delete=models.CASCADE)
    progress_step = models.IntegerField(default=0)
    base_amount = models.DecimalField(max_digits=10,decimal_places=2)
    extra_charge = models.DecimalField(max_digits=10,decimal_places=2,default=0)
    final_amount = models.DecimalField(max_digits=10,decimal_places=2)
    billing_status = models.BooleanField(default=False)
    payment_status = models.BooleanField(default=False)


    
class tbl_feedback(models.Model):
    RATING_CHOICES = (
        (1, 'Very Bad'),
        (2, 'Bad'),
        (3, 'Average'),
        (4, 'Good'),
        (5, 'Excellent'),
    )

    feedback_content = models.TextField()
    rating = models.PositiveSmallIntegerField(choices=RATING_CHOICES)
    feedback_date = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(tbl_user,on_delete=models.CASCADE,related_name='feedbacks')
    servicecenter = models.ForeignKey(tbl_servicecenter,on_delete=models.CASCADE,related_name='feedbacks')
    booking = models.OneToOneField(tbl_booking,on_delete=models.CASCADE,related_name='feedback')

    def __str__(self):
        return f"{self.servicecenter} - {self.rating}⭐"

User/views.py
from django.shortcuts import render,redirect

from Admin.models import *
from Guest.models import *
from User.models import *
from ServiceCenter.models import *
from Technician.models import *
from decimal import Decimal
from django.db.models import Sum
from datetime import date
from django.http import JsonResponse
from django.urls import reverse
from django.db.models import Avg, Count








def myprofile(request):
   if 'uid' not in request.session:
      return redirect("Guest:Login")
   else:
      userdata=tbl_user.objects.get(id=request.session['uid'])
      greeting=tbl_user.objects.get(id=request.session['uid'])
      return render(request,"User/MyProfile.html",{'Data':userdata,'greeting':greeting})



def editprofile(request):
   if 'uid' not in request.session:
      return redirect("Guest:Login")
   else:
      editprofile=tbl_user.objects.get(id=request.session['uid'])
   

      if request.method=="POST":
         name=request.POST.get("txt_name")
         email=request.POST.get("txt_email")
         contact=request.POST.get("txt_contact")
         address=request.POST.get("txt_address")
         editprofile.user_name=name
         editprofile.user_email=email
         editprofile.contact_number=contact
         editprofile.address=address
         editprofile.save()
         return render(request,"User/MyProfile.html",{'msg':"Data Updated"})
      else:
         return render(request,"User/EditProfile.html",{'editprofile':editprofile})


def changepassword(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:
      userdata=tbl_user.objects.get(id=request.session['uid'])
      dbpass=userdata.password
      if request.method=="POST":
         old=request.POST.get("txt_password")
         new=request.POST.get("new_password")
         confirm=request.POST.get("confirm_password")
         if old==dbpass:
            if new==confirm:
               userdata.password=new
               userdata.save()
               return render(request,"User/MyProfile.html",{'msg':"Password Updated"})
            else:
               return render(request,"User/ChangePassword.html",{'msg':"Invalid Password"})
         else:
            return render(request,"User/ChangePassword.html",{'msg':"Invalid Password"})
      
      else:
         return render(request,"User/ChangePassword.html",{'data':userdata})
      


def complaint(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:
      userdata=tbl_user.objects.get(id=request.session['uid'])
      complaintdata=tbl_complaint.objects.filter(user=request.session['uid'])
      if request.method=="POST":
         title=request.POST.get("txt_title")
         content=request.POST.get("txt_content")
         tbl_complaint.objects.create(complaint_title=title,complaint_content=content,user=userdata)
         return render(request,"User/HomePage.html",{'msg':"Compliant Registered"})
      else:
         return render(request,"User/Complaint.html",{'Data':complaintdata})


def delcomplaint(request,did):
   tbl_complaint.objects.get(id=did).delete()
   return redirect("User:complaint")


  
      




def homepageview(request):
   if 'uid' not in request.session:
      return redirect("Guest:Login")
   else:

      userdata=tbl_user.objects.get(id=request.session['uid'])
      return render(request,"User/HomePage.html",{'Data':userdata})




def viewservicecenter(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:

      districtdata=tbl_district.objects.all()
      greeting=tbl_user.objects.get(id=request.session['uid'])
      placedata=tbl_place.objects.all()
   
      if request.method=="POST":
         servicecenter=tbl_servicecenter.objects.filter(place=request.POST.get("sel_place"),servicecenter_status=1).annotate(avg_rating=Avg('feedbacks__rating'),total_reviews=Count('feedbacks'))
         for sc in servicecenter:
            if sc.avg_rating:
                sc.full_stars = int(sc.avg_rating)
                sc.half_star = (sc.avg_rating - sc.full_stars) >= 0.5
                sc.next_star = sc.full_stars + 1   # ← ADD THIS
            else:
                sc.full_stars = 0
                sc.half_star = False
                sc.next_star = 0

         return render(request,"User/ViewServiceCenter.html",{'servicecenter':servicecenter,'districtdata':districtdata,'placedata':placedata})

      else:
         return render(request,"User/ViewServiceCenter.html",{'districtdata':districtdata,'placedata':placedata,'greeting':greeting})


def AjaxLocation(request):
    districtid=request.GET.get('did')
    placedata=tbl_place.objects.filter(district=districtid)
    return render(request,'User/AjaxLocation.html',{'placedata':placedata})



def servicebooking(request,sid):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:

        user=tbl_user.objects.get(id=request.session['uid'])
        greeting=tbl_user.objects.get(id=request.session['uid'])
        servicecenter=tbl_servicecenter.objects.get(id=sid)
        servicetype=tbl_servicecenterservices.objects.filter(servicecenter_id=sid)
        vehicle_data=tbl_vehicle.objects.filter(user_id=request.session['uid'])
        today = date.today().isoformat()
        


        if request.method=="POST":
            todate=request.POST.get("txt_date")
            complaint=request.POST.get("txt_complaint")
            
            vehicle=tbl_vehicle.objects.get(id=request.POST.get("sel_vehicle"))
            service_ids=request.POST.getlist("services")

            booking=tbl_booking.objects.create(booking_todate=todate,booking_complaints=complaint,user=user,
            servicecenter=servicecenter,vehicle=vehicle)

            for service_id in service_ids:
                sc_service=tbl_servicecenterservices.objects.get(id=service_id)
                tbl_booking_services.objects.create(booking=booking,servicecenter_services=sc_service,
                base_amount=sc_service.base_amount)

            return render(request,"User/HomePage.html",{'msg':"Service Booked"})
        return render(request,"User/ServiceBooking.html",{'data':servicetype,'vehicle_data':vehicle_data,'greeting':greeting,'today':today})



def myservice_request(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:
      bookingdata=tbl_booking.objects.filter(user=request.session['uid']).order_by('-id')
      
      greeting=tbl_user.objects.get(id=request.session['uid'])
      
      for booking in bookingdata:
         booking.services=tbl_booking_services.objects.filter(booking=booking)

       

      return render(request,"User/MyServiceRequest.html",{'data':bookingdata,'greeting':greeting})






def AjaxVehicle(request):
    brandid=request.GET.get('bid')
    modeldata=tbl_model.objects.filter(brand=brandid)
    return render(request,'User/AjaxVehicle.html',{'modeldata':modeldata})



def vehicle(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:
      branddata=tbl_brand.objects.all()
      modeldata=tbl_model.objects.all()
      userdata=tbl_user.objects.get(id=request.session['uid'])

      if request.method=="POST":
         vehicle_number=request.POST.get("txt_number")
         year=request.POST.get("txt_year")
         model=tbl_model.objects.get(id=request.POST.get("sel_model"))
         photo=request.FILES.get("vehicle_image")
         tbl_vehicle.objects.create(vehicle_number=vehicle_number,vehicle_year=year,model=model,vehicle_photo=photo,user=userdata)
         return render(request,"User/Vehicle.html",{'msg':"Vehicle Added"})

      return render(request,"User/Vehicle.html",{'branddata':branddata,'modeldata':modeldata,'greeting':userdata})



def worknote(request,bid):
   bookingdata=tbl_booking.objects.get(id=bid)
   notes=tbl_workedescription.objects.filter(booking=bookingdata)
   return render(request,"User/ServiceNotes.html",{'notes':notes})




def payment(request, bid):

    booking = tbl_booking.objects.get(id=bid)

    services = tbl_booking_services.objects.filter(booking=booking)

    total_amount = Decimal('0.00')
    for s in services:
        total_amount += s.final_amount or Decimal('0.00')
    if not booking.booking_status == 11:
        return redirect("User:myservicerequest")

    if request.method == "POST":
        booking.booking_status = 12  
        booking.save()

        return redirect("User:myservicerequest")

    return render(
        request,
        "User/Payment.html",
        {
            "booking": booking,
            "services": services,
            "total_amount": total_amount
        }
    )


   

      



def invoice(request, bid):
    booking = tbl_booking.objects.get(id=bid)

    services = tbl_booking_services.objects.filter(booking=booking)
    worknote = tbl_workedescription.objects.filter(booking=booking)

    total_amount = services.aggregate(
        total=Sum('final_amount')
    )['total'] or 0

    return render(
        request,
        "User/Invoice.html",
        {
            'data': booking,
            'services': services,
            'worknote': worknote,
            'total': total_amount
        }
    )


def view_vehicle(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:
      vehicledata=tbl_vehicle.objects.filter(user=request.session['uid'])
      greeting=tbl_user.objects.get(id=request.session['uid'])
      return render(request,"User/MyVehicle.html",{'data':vehicledata,'greeting':greeting})



def del_vehicle(request,did):
   tbl_vehicle.objects.get(id=did).delete()
   return render(request,"User/MyVehicle.html",{'msg':"Vehicle Deleted"})


def logout(request):
   del request.session['uid']
   return redirect("Guest:Login")



def breakdown_assist(request):
    if 'uid' not in request.session:
      return redirect("Guest:Login")
    else:

      districtdata=tbl_district.objects.all()

User/templates/User/AjaxLocation.html
    <option value="">----Select----</option>
    {% for i in placedata %}
    <option value="{{i.id}}">{{i.place_name}}</option>
    {% endfor %}


    

User/templates/User/AjaxVehicle.html
    <option value="">----Select----</option>
    {% for i in modeldata %}
    <option value="{{i.id}}">{{i.model_name}}</option>
    {% endfor %}


    

User/templates/User/MyProfile.html
{% extends 'User/Head_User.html' %}
{% block content %}

<!-- My Profile Start -->
<div class="container-fluid bg-secondary booking my-5 wow fadeInUp" data-wow-delay="0.1s">
  <div class="container">
    <div class="row gx-5">

      <!-- Left Content -->
      <div class="col-lg-6 py-5">
        <div class="py-5">
          <h1 class="text-white mb-4">My Profile</h1>
          <p class="text-white mb-0">
            View and manage your personal information. Keep your contact details updated to receive service updates and confirmations.
          </p>

          <div class="mt-4 p-4 bg-primary bg-opacity-25 rounded">
            <div class="d-flex align-items-center gap-3">
              <div class="flex-shrink-0">
                <img
                  src="{{Data.image.url}}"
                  alt="Profile Picture"
                  class="rounded-circle border border-3 border-light"
                  style="width: 90px; height: 90px; object-fit: cover;"
                >
              </div>
              <div>
                <h4 class="text-white mb-1">{{Data.user_name}}</h4>
                <div class="text-white-50">{{Data.user_email}}</div>
                <div class="text-white-50">{{Data.contact_number}}</div>
              </div>
            </div>

            <div class="mt-4 d-flex flex-wrap gap-2">
              <a href="{% url 'User:editprofile' %}" class="btn btn-secondary px-4 py-2">Edit Profile</a>
              <a href="{% url 'User:changepassword' %}" class="btn btn-light px-4 py-2">Change Password</a>
            </div>
          </div>
        </div>
      </div>

      <!-- Right Details Card (Reduced size) -->
      <div class="col-lg-6">
        <!-- reduced padding from p-5 to p-4, and added centered narrower details card -->
        <div class="bg-primary h-100 p-4 wow zoomIn" data-wow-delay="0.6s">

          <!-- Smaller Photo at the TOP -->
          <div class="text-center mb-3">
            <img
              src="{{Data.image.url}}"
              alt="Profile Picture"
              class="rounded border border-3 border-light"
              style="width: 160px; height: 160px; object-fit: cover;"
            >
            <div class="text-white-50 mt-2">
              <small>Profile photo</small>
            </div>
          </div>

         <!-- Smaller heading (CENTER) -->
<div class="d-flex align-items-center justify-content-center mb-3">
  <h3 class="text-white mb-0 text-center">Profile Details</h3>
</div>


          <!-- Reduced width + padding -->
          <div class="bg-white rounded p-3 mx-auto" style="max-width: 460px;">
            <div class="row g-2">

              <div class="col-12">
                <div class="d-flex justify-content-between">
                  <span class="fw-semibold">Name</span>
                  <span class="text-muted">{{Data.user_name}}</span>
                </div>
                <hr class="my-2">
              </div>

              <div class="col-12">
                <div class="d-flex justify-content-between">
                  <span class="fw-semibold">Email</span>
                  <span class="text-muted">{{Data.user_email}}</span>
                </div>
                <hr class="my-2">
              </div>

              <div class="col-12">
                <div class="d-flex justify-content-between">
                  <span class="fw-semibold">Contact</span>
                  <span class="text-muted">{{Data.contact_number}}</span>
                </div>
                <hr class="my-2">
              </div>

              <div class="col-12">
                <div class="d-flex justify-content-between align-items-start gap-3">
                  <span class="fw-semibold">Address</span>
                  <span class="text-muted text-end" style="white-space: pre-line;">{{Data.address}}</span>
                </div>
                <hr class="my-2">
              </div>

              <!-- District -->
              <div class="col-12">
                <div class="d-flex justify-content-between align-items-center">
                  <span class="fw-semibold">District</span>
                  <span class="text-muted text-end ms-3">{{Data.place.district.district_name}}</span>
                </div>
                <hr class="my-2">
              </div>

              <!-- Place -->
              <div class="col-12">
                <div class="d-flex justify-content-between align-items-center">
                  <span class="fw-semibold">Place</span>
                  <span class="text-muted text-end ms-3">{{Data.place.place_name}}</span>
                </div>
              </div>

            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>
<!-- My Profile End -->

{% if msg %}
<script>
  alert("{{msg}}");
  window.location = "{% url 'User:MyProfile' %}";
</script>
{% endif %}

{% endblock content %}

User/templates/User/MyVehicle.html
{% extends 'User/Head_User.html' %}
{% block content %}

<style>
  :root{
    --bg: #f7d6cf;
    --card: #ffffff;
    --text: #0f172a;
    --muted: rgba(15,23,42,.65);
    --line: rgba(0,0,0,.08);

    --primary: #2f80ed;
    --danger: #eb5757;

    --shadow: 0 18px 40px rgba(0,0,0,.12);
    --shadow-soft: 0 10px 24px rgba(0,0,0,.10);

    --radius-xl: 26px;
    --radius-lg: 18px;
    --radius-md: 14px;
  }

  .veh-page{
    padding: 22px 16px 48px;
    background: radial-gradient(1200px 600px at 50% 25%, rgba(255,255,255,.45), transparent 55%),
                var(--bg);
  }

  .veh-wrap{
    max-width: 1100px;
    margin: 0 auto;
  }

  .veh-hero{
    text-align:center;
    padding: 8px 10px 16px;
  }
  .veh-hero h1{
    margin: 6px 0 6px;
    font-size: clamp(26px, 3.6vw, 44px);
    letter-spacing:-0.02em;
    font-weight: 950;
    color: var(--text);
  }
  .veh-hero p{
    margin:0 auto;
    max-width:760px;
    font-size:15px;
    color: var(--muted);
    line-height:1.55;
  }

  .veh-grid{
    display:grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 18px;
    margin-top: 14px;
  }

  .veh-card{
    background: var(--card);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow);
    border: 1px solid rgba(0,0,0,.04);
    overflow:hidden;
  }

  .veh-head{
    padding: 16px 16px 12px;
    display:flex;
    align-items:flex-start;
    justify-content: space-between;
    gap: 12px;
    background: linear-gradient(180deg, rgba(47,128,237,.10), transparent 75%);
    border-bottom: 1px solid rgba(0,0,0,.06);
  }

  .veh-title{
    margin:0;
    font-weight: 950;
    font-size: 16px;
    color: var(--text);
    line-height: 1.25;
  }
  .veh-sub{
    margin:6px 0 0;
    font-size: 12px;
    color: var(--muted);
    font-weight: 800;
  }

  .chip{
    display:inline-flex;
    align-items:center;
    gap:8px;
    padding: 9px 12px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: 950;
    border: 1px solid rgba(47,128,237,.26);
    background: rgba(47,128,237,.12);
    color: #1e5fb7;
    white-space: nowrap;
    flex-shrink: 0;
  }
  .dot{ width:10px; height:10px; border-radius:999px; background: var(--primary); }

  .veh-body{
    padding: 14px 16px 16px;
    display:grid;
    grid-template-columns: 1fr;
    gap: 12px;
  }

  .veh-media{
    border: 1px solid var(--line);
    border-radius: var(--radius-lg);
    overflow:hidden;
    box-shadow: var(--shadow-soft);
    background: #fff;
  }
  .veh-media img{
    width: 100%;
    height: 230px;
    object-fit: cover;
    display:block;
    background:#f2f2f2;
  }

  .veh-meta{
    display:grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 10px 12px;
  }

  .kv{
    border: 1px solid var(--line);
    border-radius: var(--radius-md);
    background: rgba(255,255,255,.85);
    padding: 10px 12px;
    min-width:0;
  }
  .kv small{
    display:block;
    font-size: 11px;
    text-transform: uppercase;
    letter-spacing: .02em;
    color: rgba(15,23,42,.58);
    font-weight: 950;
    margin-bottom: 4px;
  }
  .kv div{
    font-size: 13px;
    font-weight: 950;
    color: rgba(15,23,42,.90);
    overflow:hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
  .kv.full{ grid-column: 1 / -1; }

  .veh-foot{
    padding: 12px 16px 16px;
    border-top: 1px solid rgba(0,0,0,.06);
    background: rgba(255,255,255,.65);
    display:flex;
    align-items:center;
    justify-content: space-between;
    gap: 12px;
    flex-wrap: wrap;
  }

  .actions{
    display:flex;
    gap:10px;
    flex-wrap: wrap;
    justify-content:flex-end;
  }

  .btnx{
    display:inline-flex;
    align-items:center;
    justify-content:center;
    height: 36px;
    padding: 0 14px;
    border-radius: 12px;
    font-weight: 950;
    font-size: 13px;
    text-decoration:none;
    border: 1px solid rgba(15,23,42,.12);
    background: rgba(255,255,255,.80);
    color: rgba(15,23,42,.82);
    cursor:pointer;
  }
  .btnx.primary{
    border-color: rgba(47,128,237,.28);
    background: rgba(47,128,237,.12);
    color: #1e5fb7;
  }
  .btnx.danger{
    border-color: rgba(235,87,87,.28);
    background: rgba(235,87,87,.12);
    color: #b13a3a;
  }

  .empty{
    background: var(--card);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow);
    border: 1px dashed rgba(0,0,0,.14);
    padding: 18px;
    text-align:center;
    color: rgba(15,23,42,.70);
    font-weight: 900;
  }

  @media (max-width: 980px){
    .veh-grid{ grid-template-columns: 1fr; }
    .veh-meta{ grid-template-columns: 1fr; }
  }
</style>

<div class="veh-page">
  <div class="veh-wrap">

    <div class="veh-hero">
      <h1> Vehicle Information</h1>
      <p></p>
    </div>

    <form method="post">
      {% csrf_token %}

      <div class="veh-grid">
        {% for i in data %}
        <div class="veh-card">

          <div class="veh-head">
            <div style="min-width:0;">
              <p class="veh-title">{{ i.model.brand.brand_name }} {{ i.model.model_name }}</p>
              <p class="veh-sub">Registration: {{ i.vehicle_number }}</p>
            </div>
            <div class="chip">
              <span class="dot"></span>
              <span>Year: {{ i.vehicle_year }}</span>
            </div>
          </div>

          <div class="veh-body">
            <div class="veh-media">
              <img src="{{ i.vehicle_photo.url }}" alt="Vehicle Image">
            </div>

            <div class="veh-meta">
              <div class="kv">
                <small>Brand</small>
                <div>{{ i.model.brand.brand_name }}</div>
              </div>
              <div class="kv">
                <small>Model</small>
                <div>{{ i.model.model_name }}</div>
              </div>
              <div class="kv">
                <small>Registration No.</small>
                <div>{{ i.vehicle_number }}</div>
              </div>
              <div class="kv">
                <small>Year</small>
                <div>{{ i.vehicle_year }}</div>
              </div>
            </div>
          </div>

          <div class="veh-foot">
            <div style="font-size:12px; font-weight:850; color: rgba(15,23,42,.62);">
              Keep details updated for accurate service records.
            </div>
            
            <a href="{% url 'User:service_history' i.id %}" 
   class="btn btn-sm btn-primary">
   <i class="fa-solid fa-clock-rotate-left me-1"></i>
   Service History
</a>


            <div class="actions">
            
             
              <a href="{% url 'User:delvehicle' i.id %}" class="btnx danger"
                 onclick="return confirm('Delete this vehicle?');">Delete</a>
            </div>
          </div>

        </div>
        {% empty %}
          <div class="empty">
            No vehicles added yet.
          </div>
        {% endfor %}
      </div>
    </form>

  </div>
</div>

{% if msg %}
<script>
  alert("{{msg}}");
  window.location = "{% url 'User:myvehicle' %}";
</script>
{% endif %}

{% endblock %}