GarageLive/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Guest.urls')),  # 👈 DEFAULT HOMEPAGE
    path('admin/', admin.site.urls),
    
    path('Admin/',include('Admin.urls')),
    path('Guest/',include('Guest.urls')),
    path('User/',include('User.urls')),
    
    path('ServiceCenter/',include('ServiceCenter.urls')),
    path('Technician/',include('Technician.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ServiceCenter/urls.py
from django.urls import path
from ServiceCenter import views

app_name="ServiceCenter"

urlpatterns = [
     path('HomePage/',views.homepage,name="HomePage"),
     path('Profile/',views.profile,name="profile"),
     path('editprofile/',views.editprofile,name="editprofile"),
     path('changepassword/',views.changepassword,name="changepassword"),
     path('technician/',views.technician,name="technician"),
     path('deltechnician/<int:did>',views.deltechnician,name="deltechnician"),

     path('myservices/',views.myservices,name="myservices"),
     path('editmy_services/<int:sid>',views.editmy_services,name="editmy_services"),
     path('delmyservices/<int:did>',views.delmyservices,name="delmyservices"),

     path('service_request/',views.service_requests,name="service_request"),
     path('acceptrequest/<int:aid>',views.acceptrequest,name="acceptrequest"),
     path('rejectrequest/<int:rid>',views.rejectrequest,name="rejectrequest"),

     path('assign_technician/<int:bid>',views.assign_technician,name="assign_technician"),
     path('assignjob/<int:tid>/<int:bid>',views.assignjob,name="assignjob"),
     path('generate_bill/<int:bid>',views.generate_bill,name="generate_bill"),
     path('logout/',views.logout,name="logout"),

     path('breakdownrequest/',views.breakdown_requests,name="breakdownrequest"),
     path('acceptbreakdown/<int:aid>',views.acceptbreakdown,name="acceptbreakdown"),
     path('rejectbreakdown/<int:rid>',views.rejectbreakdown,name="rejectbreakdown"),
     path('breakdown_technician/<int:btid>',views.breakdown_technician,name="breakdown_technician"),
     path('assign_breakdown/<int:tid>/<int:btid>',views.assign_breakdown,name="assign_breakdown"),

     path('my-breakdown-services/', views.my_breakdown_services, name='my_breakdown_services'),

     path('edit-breakdown-service/<int:sid>/',views.edit_breakdown_service,name='edit_breakdown_service'),

     path('delete-breakdown-service/<int:did>/',views.delete_breakdown_service,name='delete_breakdown_service'),
     path('view_feedback/',views.view_feedback,name="view_feedback"),

     path('chart-homepage/', views.chart_homepage, name='chart_homepage'),
     path('weekly-income-chart/', views.weekly_income_chart, name='weekly_income_chart'),
     path('api/service-requests/', views.servicecenter_request_api, name="servicecenter_api"),
     path('api/breakdown-requests/', views.servicecenter_breakdown_api, name="breakdown_api"),
     path('api/homepage-alerts/', views.homepage_alert_api, name='homepage_alerts'),
     
    

     
     


     


     




]

Technician/urls.py
from django.urls import path
from Technician import views

app_name="Technician"

urlpatterns = [
     path('HomePage/',views.homepage,name="HomePage"),
     path('profile/',views.profile,name="profile"),
     path('editprofile/',views.editprofile,name="editprofile"),
     path('changepassword/',views.changepassword,name="changepassword"),
     path('assignedjobs/',views.assigned_jobs,name="assigned_jobs"),
     path('startwork/<int:sid>',views.startwork,name="startwork"),
     path('startdiagnosis/<int:did>',views.start_diagnosis,name="start_diagnosis"),
     path('diagnosis_completed/<int:cdid>',views.diagnosis_completed,name="diagnosis_completed"),
     path('repair_progress/<int:rid>',views.repair_progress,name="repair_progress"),
     path('parts_replaced/<int:pid>',views.parts_replaced,name="parts_replaced"),
     path('testing_QA/<int:tid>',views.testing_QA,name="testing_QA"),
     path('service_completed/<int:sid>',views.service_completed,name="service_completed"),
     path('out_delivery/<int:did>',views.out_delivery,name="out_delivery"),
     # path('delivered/<int:did>',views.delivered,name="delivered"),
     path('workdescription/<int:bid>',views.workdescription,name="workdescription"),
     path('logout/',views.logout,name="logout"),

     path('update-service-cost/<int:booking_id>/', views.update_service_cost, name='update_service_cost'),

     path('breakdown-jobs/',views.breakdown_jobs,name='breakdown_jobs'),
      
     path('breakdown-step/<int:sid>/', views.update_breakdown_step, name='update_breakdown_step'),
     path('update_breakdown_charge/<int:bs_id>',views.update_breakdown_charge,name="update_breakdown_charge"),

    




     
]

User/urls.py
from django.urls import path
from User import views

app_name="User"

urlpatterns = [
    path('MyProfile/',views.myprofile,name="MyProfile"),
    path('editprofile/',views.editprofile,name="editprofile"),
    path('ChangePassword/',views.changepassword,name="changepassword"),
    path('HomePage/',views.homepageview,name="HomePage"),
    path('Complaint/',views.complaint,name="complaint"),
    path('delcomplaint/<int:did>',views.delcomplaint,name="delcomplaint"),

    path('viewservicecenter/',views.viewservicecenter,name="viewservicecenter"),
    path('AjaxLocation/',views.AjaxLocation,name="AjaxLocation"),
    path('servicebooking/<int:sid>',views.servicebooking,name="servicebooking"),
    path('myservicerequest/',views.myservice_request,name="myservicerequest"),
    

    path('AjaxVehicle/',views.AjaxVehicle,name="AjaxVehicle"),
    path('vehicle/',views.vehicle,name="vehicle"),
    path('worknote/<int:bid>',views.worknote,name="worknote"),
    path('payment/<int:bid>',views.payment,name="payment"),
    path('invoice/<int:bid>',views.invoice,name="invoice"),
    path('view_vehicle/',views.view_vehicle,name="myvehicle"),

    path('delvehicle/<int:did>',views.del_vehicle,name="delvehicle"),
    path('logout/',views.logout,name="logout"),

    path('breakdownassist/',views.breakdown_assist,name='breakdownassist'),
    path('BreakdownBooking/<int:sid>',views.breakdown_booking,name='BreakdownBooking'),
    path('breakdown_status/',views.breakdown_status,name="breakdown_status"),
    path("breakdown-payment/<int:bs_id>/",views.breakdown_payment,name="breakdown_payment"),
    path("breakdown-invoice/<int:bs_id>/",views.breakdown_invoice,name="breakdown_invoice"),
    path('feedback/<int:bid>/',views.feedback,name="feedback"),
    path('edit-feedback/<int:fid>/',views.edit_feedback,name="edit_feedback"),
    path('delete-feedback/<int:fid>/',views.delete_feedback,name="delete_feedback"),
    path('service_history/<int:vid>/',views.service_history,name="service_history"),
    path('breakdown-status-api/', views.breakdown_status_api, name='breakdown_status_api'),
    path('myservice-request-api/', views.myservice_request_api, name='myservice_request_api'),
    



    
   
]

Technician/models.py
from django.db import models
from User.models import *

# Create your models here.

class tbl_workedescription(models.Model):
    workedesc_content=models.CharField(max_length=50)
    booking=models.ForeignKey(tbl_booking,on_delete=models.CASCADE)
    
    

ServiceCenter/views.py
from django.shortcuts import render,redirect
from Guest.models import *
from ServiceCenter.models import *
from Admin.models import *
from User.models import *
from decimal import Decimal
from datetime import date, timedelta
from django.db.models import Count
from django.db.models import Q
from django.http import JsonResponse
import calendar
from django.db.models import Sum
from collections import defaultdict







# Create your views here.

def homepage(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:
        centerdata=tbl_servicecenter.objects.get(id=request.session['cid'])
        today = date.today()
       
        
        active_jobs = tbl_booking.objects.filter(servicecenter=centerdata).filter(Q(booking_status=1) | Q(booking_status__gte=3, booking_status__lt=12)).count()
        active_breakdown_jobs=tbl_breakdownassist.objects.filter(servicecenter=centerdata, breakdown_status=1).count()
        
        pending_service_approvals=tbl_booking.objects.filter(servicecenter=centerdata, booking_status=0).count()
        pending_breakdown_approvals=tbl_breakdownassist.objects.filter(servicecenter=centerdata, breakdown_status=0).count()
        customer_feedback_count = tbl_feedback.objects.filter(servicecenter=centerdata,feedback_date__month=today.month,feedback_date__year=today.year).count()
        technicians = tbl_technician.objects.filter(servicecenter=centerdata)
        busy_tech_ids=get_busy_technician_ids(centerdata)

        technician_status_list = []
        for tech in technicians:
            service_completed=tbl_booking.objects.filter(servicecenter=centerdata,technician=tech,booking_status=12).count()
            breakdown_completed=tbl_breakdownassist.objects.filter(servicecenter=centerdata,technician=tech,breakdown_status=3).count()
            total_completed= service_completed+ breakdown_completed
            is_busy = tech.id in busy_tech_ids
            technician_status_list.append({"technician": tech,"is_busy": is_busy,"total_completed": total_completed})
        technician_status_list.sort(key=lambda x: x['total_completed'],reverse=True)





        return render(request,"ServiceCenter/HomePage.html",{'data':centerdata,
        'active_jobs':active_jobs,'pending_service_approvals':pending_service_approvals,'pending_breakdown_approvals':pending_breakdown_approvals,'customer_feedback_count':customer_feedback_count,
        'active_breakdown_jobs':active_breakdown_jobs,"technician_status_list": technician_status_list})



def profile(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:
        centerdata=tbl_servicecenter.objects.get(id=request.session['cid'])
        return render(request,"ServiceCenter/Profile.html",{'Data':centerdata})


def editprofile(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:
        editprofile=tbl_servicecenter.objects.get(id=request.session['cid'])
        if request.method=="POST":
            name=request.POST.get("txt_name")
            email=request.POST.get("txt_email")
            contact=request.POST.get("txt_contact")
            address=request.POST.get("txt_address")
            logo=request.FILES.get("file_logo")
            editprofile.servicecenter_name=name
            editprofile.servicecenter_email=email
            editprofile.servicecenter_contact=contact
            editprofile.servicecenter_address=address
            editprofile.servicecenter_logo=logo
            editprofile.save()
            return render(request,"ServiceCenter/Profile.html",{'msg':"Record Updated"})
        else:
            return render(request,"ServiceCenter/EditProfile.html",{'Data':editprofile})



def changepassword(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:

        changepass=tbl_servicecenter.objects.get(id=request.session['cid'])
        dbpass=changepass.servicecenter_password
        if request.method=="POST":
            old=request.POST.get("txt_password")
            new=request.POST.get("new_password")
            confirm=request.POST.get("confirm_password")
            if old==dbpass:
                if new==confirm:
                    changepass.servicecenter_password=new
                    changepass.save()
                    return render(request,"ServiceCenter/Profile.html",{'msg':"Password Updated"})
                else:
                    return render(request,"ServiceCenter/ChangePassword.html",{'msg':"Invalid Password"})
            else:
                return render(request,"ServiceCenter/ChangePassword.html",{'msg':"Passwords dont match"})
            
        else:
            return render(request,"ServiceCenter/ChangePassword.html",{'Data':changepass})



def technician(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:
        techniciandata=tbl_technician.objects.filter(servicecenter=request.session['cid'])
        servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
        if request.method=="POST":
            name=request.POST.get("txt_name")
            email=request.POST.get("txt_mail")
            contact=request.POST.get("txt_contact")
            photo=request.FILES.get("photo")
            password=request.POST.get("txt_password")

            techniciancount=tbl_technician.objects.filter(technician_email=email).count()
            if techniciancount>0:
                return render(request,"ServiceCenter/Technician.html",{'msg':"email already exists"})
            else:

                tbl_technician.objects.create(technician_name=name,technician_email=email,technician_contact=contact,
                technician_photo=photo,technician_password=password,servicecenter=servicecenter)
                return render(request,"ServiceCenter/Technician.html",{'msg':"Technician Added"})
        else:
            return render(request,"ServiceCenter/Technician.html",{'data':techniciandata,'Data':servicecenter})


def deltechnician(request,did):
    tbl_technician.objects.get(id=did).delete()
    return render(request,"ServiceCenter/Technician.html",{'msg':"Technician Removed"})



def myservices(request):
     if 'cid' not in request.session:
      return redirect("Guest:Login")
     else:
        servicetype=tbl_servicetype.objects.all()
        servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
        myservices=tbl_servicecenterservices.objects.filter(servicecenter=request.session['cid'])
        if request.method=="POST":
            service_type=tbl_servicetype.objects.get(id=request.POST.get("sel_servicetype"))
            servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
            base_amount=request.POST.get("base_amount")
            tbl_servicecenterservices.objects.create(servicetype=service_type,servicecenter=servicecenter,base_amount=base_amount)
            return render(request,"ServiceCenter/MyServices.html",{'msg':"Service added"})
        else:
            return render(request,"ServiceCenter/MyServices.html",{'data':servicetype,'myservices':myservices,'Data':servicecenter})



def editmy_services(request, sid):
    editservice = tbl_servicecenterservices.objects.get(id=sid)
    servicetype = tbl_servicetype.objects.all()   
    myservices = tbl_servicecenterservices.objects.filter(servicecenter=request.session['cid']) 
    servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
    if request.method == "POST":
        base_amount = request.POST.get("base_amount")
        editservice.base_amount = base_amount
        editservice.save()
        return redirect("ServiceCenter:myservices")
    else:
        return render(request, "ServiceCenter/MyServices.html", {
            'editservice': editservice,
            'data': servicetype,        
            'myservices': myservices,'Data':servicecenter    
        })

        

        


def delmyservices(request,did):
    tbl_servicecenterservices.objects.get(id=did).delete()
    return redirect("ServiceCenter:myservices")


def service_requests(request):
    if 'cid' not in request.session:
      return redirect("Guest:Login")
    else:
        servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
        bookingdata=tbl_booking.objects.filter(servicecenter_id=request.session['cid']).order_by('-id')
        for booking in bookingdata:
            booking.services=tbl_booking_services.objects.filter(booking=booking)
        return render(request,"ServiceCenter/ServiceRequest.html",{'data':bookingdata,'Data': servicecenter})



def acceptrequest(request,aid):
    data=tbl_booking.objects.get(id=aid)
    data.booking_status=1
    data.save()
    return render(request,"ServiceCenter/ServiceRequest.html",{'msg':"Request Accepted"})


def rejectrequest(request,rid):
    data=tbl_booking.objects.get(id=rid)
    data.booking_status=2
    data.save()
    return render(request,"ServiceCenter/ServiceRequest.html",{'msg':"Request Rejected"})


def assign_technician(request,bid):
    technician_data=tbl_technician.objects.filter(servicecenter=request.session['cid'])
    servicecenter=tbl_servicecenter.objects.get(id=request.session['cid'])
    busy_ids = get_busy_technician_ids(servicecenter)
    return render(request,"ServiceCenter/AssignTechnician.html",{'data':technician_data,'bid':bid,'busy_ids': list(busy_ids),'mode': 'service','Data':servicecenter})

def assignjob(request,tid,bid):
    technician=tbl_technician.objects.get(id=tid)
    booking=tbl_booking.objects.get(id=bid)
    booking.technician_id=technician
    booking.save()

    return render(request,"ServiceCenter/ServiceRequest.html",{'msg':"Technician Assigned"})





def generate_bill(request, bid):

    booking = tbl_booking.objects.get(id=bid)
    data=tbl_servicecenter.objects.get(id=request.session['cid'])
    services = tbl_booking_services.objects.filter(booking=booking)

ServiceCenter/templates/ServiceCenter/ChangePassword.html
{% extends 'ServiceCenter/Head_service.html' %}
{% block content %}

<style>
  .hint-text{ font-size: .85rem; color: #6c757d; }
</style>

<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">
      <div class="col-lg-6 mx-auto grid-margin stretch-card">
        <div class="card">
          <div class="card-body">

            <div class="d-flex align-items-center justify-content-between mb-2">
              <div>
                <h4 class="card-title mb-1">Change Password</h4>
                <p class="card-description mb-0">Update your account password securely</p>
              </div>
              <a href="{% url 'ServiceCenter:profile' %}" class="btn btn-light">Back</a>
            </div>

            <hr>

            <form method="post" class="forms-sample">
              {% csrf_token %}

              <div class="form-group">
                <label for="old_password">Old Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="old_password"
                  name="txt_password"
                  placeholder="Enter old password"
                  required
                >
              </div>

              <div class="form-group">
                <label for="new_password">New Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="new_password"
                  name="new_password"
                  placeholder="Enter new password"
                  required
                >
                <div class="hint-text mt-2">Use a strong password with letters, numbers, and symbols.</div>
              </div>

              <div class="form-group">
                <label for="confirm_password">Re-Type Password</label>
                <input
                  type="password"
                  class="form-control"
                  id="confirm_password"
                  name="confirm_password"
                  placeholder="Re-enter new password"
                  required
                >
              </div>

              <div class="d-flex gap-2">
                <button type="submit" class="btn btn-primary me-2">
                  Change Password
                </button>
                <a href="{% url 'ServiceCenter:profile' %}" class="btn btn-light">
                  Cancel
                </a>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'ServiceCenter:changepassword' %}";
</script>
{% endif %}

{% endblock content %}

ServiceCenter/templates/ServiceCenter/MyBreakdownServices.html
{% extends 'ServiceCenter/Head_service.html' %}
{% block content %}

<style>
  td.action-cell { white-space: nowrap; }
</style>

<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">

      <!-- ================= ADD BREAKDOWN SERVICE CARD ================= -->
      <div class="col-md-4 grid-margin stretch-card">
        <div class="card shadow-sm">
          <div class="card-body">

            <h4 class="card-title">My Breakdown Services</h4>
            <p class="card-description mb-3">
              Add breakdown services offered by your service center
            </p>

            <form method="post" class="forms-sample">
              {% csrf_token %}

              <!-- Breakdown Service Type -->
              <div class="form-group">
                <label for="sel_servicetype">Breakdown Service Type</label>
                <select class="form-control"
                        name="sel_servicetype"
                        id="sel_servicetype"
                        required>
                  <option value="">-- Select Breakdown Service --</option>
                  {% for i in data %}
                    <option value="{{ i.id }}"
                      {% if editservice and i.id == editservice.servicetype.id %}selected{% endif %}>
                      {{ i.servicetype_name }}
                    </option>
                  {% endfor %}
                </select>
              </div>

              <!-- Base Amount -->
              <div class="form-group">
                <label for="base_amount">Base Amount (₹)</label>
                <input type="number"
                       class="form-control"
                       name="base_amount"
                       id="base_amount"
                       min="0"
                       step="0.01"
                       placeholder="Enter base price"
                       value="{{ editservice.base_amount|default:'' }}"
                       required>
              </div>

              <div class="mt-3">
                <button type="submit" class="btn btn-primary me-2">
                  Submit
                </button>

                <br><br>

                <a href="{% url 'ServiceCenter:my_breakdown_services' %}"
                   class="btn btn-danger">
                  Cancel
                </a>
              </div>

            </form>

          </div>
        </div>
      </div>

      <!-- ================= MY BREAKDOWN SERVICES LIST ================= -->
      <div class="col-md-8 grid-margin stretch-card">
        <div class="card shadow-sm">
          <div class="card-body">

            <div class="d-flex align-items-center justify-content-between mb-3">
              <div>
                <h4 class="card-title mb-1">My Breakdown Service List</h4>
                <p class="card-description mb-0">
                  Breakdown services currently offered by your center
                </p>
              </div>
            </div>

            <div class="table-responsive">
              <table class="table table-hover align-middle">
                <thead class="table-light">
                  <tr>
                    <th style="width:70px;">#</th>
                    <th>Breakdown Service</th>
                    <th>Base Amount (₹)</th>
                    <th class="text-center" style="width:140px;" colspan="2">
                      Action
                    </th>
                  </tr>
                </thead>

                <tbody>
                  {% for i in myservices %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ i.servicetype.servicetype_name }}</td>
                    <td>₹ {{ i.base_amount }}</td>

                    <td class="text-center action-cell">
                      <a href="{% url 'ServiceCenter:edit_breakdown_service' i.id %}"
                         class="btn btn-sm btn-outline-primary">
                        Edit
                      </a>
                    </td>

                    <td class="text-center action-cell">
                      <a href="{% url 'ServiceCenter:delete_breakdown_service' i.id %}"
                         class="btn btn-sm btn-outline-danger"
                         onclick="return confirm('Remove this breakdown service?');">
                        Delete
                      </a>
                    </td>
                  </tr>

                  {% empty %}
                  <tr>
                    <td colspan="4"
                        class="text-center text-muted py-4">
                      No breakdown services added yet.
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>

              </table>
            </div>

          </div>
        </div>
      </div>

    </div>

  </div>
</div>

<!-- ================= ALERT MESSAGE ================= -->
{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'ServiceCenter:my_breakdown_services' %}";
</script>
{% endif %}

{% endblock content %}

ServiceCenter/templates/ServiceCenter/Profile.html
{% extends 'ServiceCenter/Head_service.html' %}
{% block content %}

<style>
  /* Profile page styling (clean service-center look) */
  .profile-avatar{
    width: 86px;
    height: 86px;
    border-radius: 18px;
    object-fit: cover;
    border: 1px solid rgba(0,0,0,.10);
    background: #fff;
  }
  .doc-thumb{
    width: 90px;
    height: 90px;
    border-radius: 16px;
    object-fit: cover;
    border: 1px solid rgba(0,0,0,.10);
    background: #fff;
  }
  .kv-label{
    font-size: .78rem;
    font-weight: 600;
    letter-spacing: .02em;
    color: #6c757d;
    margin-bottom: 6px;
  }
  .kv-value{
    background: #f8f9fa;
    border: 1px solid rgba(0,0,0,.08);
    border-radius: 14px;
    padding: 12px 14px;
    color: #212529;
    line-height: 1.35;
    word-break: break-word;
  }
  .addr-box{
    background: #f8f9fa;
    border: 1px solid rgba(0,0,0,.08);
    border-radius: 14px;
    padding: 12px 14px;
    min-height: 74px;
    color: #212529;
    line-height: 1.35;
    white-space: pre-wrap;
  }
  .info-grid{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 14px;
  }
  @media (max-width: 992px){
    .info-grid{ grid-template-columns: 1fr; }
  }
  .action-row{ gap: 10px; }
</style>

<div class="main-panel">
  <div class="content-wrapper">

    <div class="row">
      <div class="col-lg-10 mx-auto grid-margin stretch-card">
        <div class="card">
          <div class="card-body">

            <!-- Header -->
            <div class="d-flex align-items-center justify-content-between flex-wrap mb-3">
              <div class="d-flex align-items-center">
                <div class="me-3">
                  <img src="{{ Data.servicecenter_logo.url }}" alt="logo" class="profile-avatar">
                </div>
                <div>
                  <h4 class="card-title mb-1">{{ Data.servicecenter_name }}</h4>
                  <p class="card-description mb-0">
                    {{ Data.place.district.district_name }} • {{ Data.place.place_name }}
                  </p>
                </div>
              </div>

              <div class="d-flex action-row mt-2 mt-md-0">
                <a href="{% url 'ServiceCenter:editprofile' %}" class="btn btn-outline-primary">
                  Edit Profile
                </a>
                <a href="{% url 'ServiceCenter:changepassword' %}" class="btn btn-outline-warning">
                  Change Password
                </a>
              </div>
            </div>

            <hr>

            <form method="post">
              {% csrf_token %}

              <!-- Info Grid -->
              <div class="info-grid mt-3">

                <div>
                  <div class="kv-label">Email</div>
                  <div class="kv-value">{{ Data.servicecenter_email }}</div>
                </div>

                <div>
                  <div class="kv-label">Contact</div>
                  <div class="kv-value">{{ Data.servicecenter_contact }}</div>
                </div>

                <div>
                  <div class="kv-label">District</div>
                  <div class="kv-value">{{ Data.place.district.district_name }}</div>
                </div>

                <div>
                  <div class="kv-label">Place</div>
                  <div class="kv-value">{{ Data.place.place_name }}</div>
                </div>

                <div>
                  <div class="kv-label">Date of Join</div>
                  <div class="kv-value">{{ Data.servicecenter_regdate }}</div>
                </div>

                <div>
                  <div class="kv-label">Account Status</div>
                  <div class="kv-value">
                    {% if Data.servicecenter_status == 1 %}
                      <span class="badge badge-success">Verified</span>
                    {% elif Data.servicecenter_status == 2 %}
                      <span class="badge badge-danger">Rejected</span>
                    {% else %}
                      <span class="badge badge-warning">Pending</span>
                    {% endif %}
                  </div>
                </div>

                <div style="grid-column: 1 / -1;">
                  <div class="kv-label">Address</div>
                  <div class="addr-box">{{ Data.servicecenter_address }}</div>
                </div>

              </div>

              <!-- Documents -->
              <div class="row mt-4">
                <div class="col-md-6 mb-3">
                  <div class="kv-label">Logo</div>
                  <div class="kv-value d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center">
                      <img src="{{ Data.servicecenter_logo.url }}" alt="logo" class="doc-thumb me-3">
                      <div>
                        <div class="fw-semibold">Service Center Logo</div>
                        <div class="text-muted" style="font-size:.85rem;">Click to view full image</div>
                      </div>
                    </div>
                    <a href="{{ Data.servicecenter_logo.url }}" target="_blank" class="btn btn-sm btn-light">
                      View
                    </a>
                  </div>
                </div>

                <div class="col-md-6 mb-3">
                  <div class="kv-label">License Proof</div>
                  <div class="kv-value d-flex align-items-center justify-content-between">
                    <div class="d-flex align-items-center">
                      <img src="{{ Data.servicecenter_license.url }}" alt="license" class="doc-thumb me-3">
                      <div>
                        <div class="fw-semibold">License Document</div>
                        <div class="text-muted" style="font-size:.85rem;">Click to view full image</div>
                      </div>
                    </div>
                    <a href="{{ Data.servicecenter_license.url }}" target="_blank" class="btn btn-sm btn-light">
                      View
                    </a>
                  </div>
                </div>
              </div>

            </form>

          </div>
        </div>
      </div>
    </div>

  </div>
</div>

{% if msg %}
<script>
  alert("{{ msg }}");
  window.location = "{% url 'ServiceCenter:profile' %}";
</script>
{% endif %}

{% endblock content %}